# Generated by Django 4.0 on 2024-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='price',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=5, null=True),
        ),
    ]
