# Generated by Django 4.0 on 2024-12-10 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_imagemodel_price_imagemodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Rate between 1 and 5 stars.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
